package com.android.internal.telephony.cdma.sms;

public final class SmsEnvelope {
    public static final int MESSAGE_TYPE_ACKNOWLEDGE = 2;
    public static final int MESSAGE_TYPE_BROADCAST = 1;
    public static final int MESSAGE_TYPE_POINT_TO_POINT = 0;
    public static final int SERVICE_CATEGORY_CMAS_CHILD_ABDUCTION_EMERGENCY = 4099;
    public static final int SERVICE_CATEGORY_CMAS_EXTREME_THREAT = 4097;
    public static final int SERVICE_CATEGORY_CMAS_LAST_RESERVED_VALUE = 4351;
    public static final int SERVICE_CATEGORY_CMAS_PRESIDENTIAL_LEVEL_ALERT = 4096;
    public static final int SERVICE_CATEGORY_CMAS_SEVERE_THREAT = 4098;
    public static final int SERVICE_CATEGORY_CMAS_TEST_MESSAGE = 4100;
    public static final int TELESERVICE_CATPT = 4103;
    public static final int TELESERVICE_CPT = 4097;
    public static final int TELESERVICE_IMSST = 4242;
    public static final int TELESERVICE_LGT_CBS_32576 = 32576;
    public static final int TELESERVICE_LGT_CBS_327680 = 327680;
    public static final int TELESERVICE_LGT_ETC_SHARE_49162 = 49162;
    public static final int TELESERVICE_LGT_FOTA_SMS = 49783;
    public static final int TELESERVICE_LGT_LMS_63230 = 63230;
    public static final int TELESERVICE_LGT_PCS_PAGING_TID_4097 = 4097;
    public static final int TELESERVICE_LGT_WAP_M_NOTI_IND_49173 = 49173;
    public static final int TELESERVICE_LGT_WAP_URL_NOTI_49166 = 49166;
    public static final int TELESERVICE_LGT_WAP_URL_NOTI_49167 = 49167;
    public static final int TELESERVICE_LGT_WAP_URL_NOTI_49168 = 49168;
    public static final int TELESERVICE_LGT_WEB_CP_49767 = 49767;
    public static final int TELESERVICE_LGT_WEB_LGT_49765 = 49765;
    public static final int TELESERVICE_LGT_WEB_THIRD_49763 = 49763;
    public static final int TELESERVICE_MWI = 262144;
    public static final int TELESERVICE_NOT_SET = 0;
    public static final int TELESERVICE_SCPT = 4102;
    public static final int TELESERVICE_VMN = 4099;
    public static final int TELESERVICE_WAP = 4100;
    public static final int TELESERVICE_WAP_CTC = 65002;
    public static final int TELESERVICE_WAP_CTC_DM = 65009;
    public static final int TELESERVICE_WEMT = 4101;
    public static final int TELESERVICE_WMT = 4098;
    public byte[] bearerData;
    public int bearerReply;
    public byte causeCode;
    public CdmaSmsAddress destAddress;
    public byte errorClass;
    public int messageType;
    public CdmaSmsAddress origAddress;
    public CdmaSmsSubaddress origSubaddress;
    public byte replySeqNo;
    public int serviceCategory;
    public int teleService = 0;
}
